######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 10 07:42:54 2009
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
VERSION = 4.0.5

# Input
HEADERS += fparser.hh fpconfig.hh fptypes.hh
SOURCES += example.cc fparser.cc fpoptimizer.cc
